@extends('layouts.app')
@section('title', 'Addina – Home')
@section('content')
  @include('components.hero')
  @include('components.features')
  @include('components.promo-banners')
  @include('components.featured-products')
  @include('components.hot-deal')
  @include('components.trendy-collection')
  @include('components.deal-banners')
  @include('components.testimonials')
  @include('components.recent-blog')
  @include('components.cta-section')
@endsection